apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: calendar
spec:
  eventBusName: codefresh-eventbus
  calendar:
    by-interval:
      # creates an event every 10 seconds
      interval: 10s

#
#    example-with-schedule:
#      # schedules an event at 30 minutes past each hour
#      schedule: "30 * * * *"
#
#    schedule-with-static-user-payload:
#      schedule: "30 * * * *"
#      # userPayload is a static string that will be send to the sensor with each event payload
#      # whatever you put here is blindly delivered to sensor.
#      # access in resourceParameters or templateParameters via the path userPayload.hello
#      userPayload: {"hello": "world"}