# The following workflow executes a diamond workflow
# 
#   A
#  / \
# B   C
#  \ /
#   D

apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: spawn-diamond-wf
  namespace: prod-runtime
spec:
  template:
    serviceAccountName: codefresh-sa
  eventBusName: codefresh-eventbus
  dependencies:
    - name: git-push
      eventSourceName: github
      eventName: example
  triggers:
    - template:
        name: trigger-1
        conditions: git-push
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: dag-diamond-
              spec:
                serviceAccountName: codefresh-sa
                entrypoint: diamond
                templates:
                - name: diamond
                  dag:
                    tasks:
                    - name: A
                      template: echo
                      arguments:
                        parameters: [{name: message, value: A}]
                    - name: B
                      depends: "A"
                      template: echo
                      arguments:
                        parameters: [{name: message, value: B}]
                    - name: C
                      depends: "A"
                      template: echo
                      arguments:
                        parameters: [{name: message, value: C}]
                    - name: D
                      depends: "B && C"
                      template: echo
                      arguments:
                        parameters: [{name: message, value: D}]

                - name: echo
                  inputs:
                    parameters:
                    - name: message
                  container:
                    image: alpine:3.7
                    command: [sh, -c]
                    args: ["sleep 10; echo {{inputs.parameters.message}}"]
